### ISSUE TITLE
Cannot get it to work with NextJs version >=10.0.6. Works fine with NextJs 10.0.5.

### ISSUE THREAD

**Issue by thiraphong-c** [isaachinman/next-i18next#1076]
## Describe the bug
```bash
warn  next-i18next/node_modules/i18next-fs-backend/cjs/readFile.js
Critical dependency: the request of a dependency is an expression
next-i18next/dist/commonjs/serverSideTranslations.js
Critical dependency: the request of a dependency is an expression

Error: Cannot find module '/Users/username/Development/test/next-i18next/examples/simple/next-i18next.config.js'
    at webpackEmptyContext (eval at ../../dist/commonjs sync recursive (/Users/username/Development/test/next-i18next/examples/simple/.next/server/pages/index.js:103:1), <anonymous>:2:10)
    at eval (webpack-internal:///../../dist/commonjs/serverSideTranslations.js:102:120)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  code: 'MODULE_NOT_FOUND'
}
```

## Occurs in next-i18next version
8.1.2

## Steps to reproduce
1. Clone this repo
2. upgrade next version in examples/simple/package.json to 10.0.6 or 10.0.7 or 10.0.8 or 10.0.9
3. run `yarn run-example` or `yarn test`

## Expected behaviour
The example app to successfully demo next-i18next.

## Screenshots
If applicable, add screenshots or a GIF to help explain your problem.

## OS (please complete the following information)
 - Device: [e.g. MBP 2018 13"]
 - Browser: [e.g. Chrome 70.0.3538.77]

**Comment by isaachinman** [comment]
Hi @thiraphong-c – can you please open an issue on the NextJs repo? If v10.0.5 works, but >=v10.0.6 does not, I would argue that they have broken semver and need to release a bug fix.

**Comment by Pomevak** [comment]
Hi, is this issue resolved? I also encountered this issue, but in my case, the same error arouses even with next.js 10.0.5

**Comment by isaachinman** [comment]
@Pomevak I haven't heard from @thiraphong-c. Can you please open an issue on the NextJs repository with steps to reproduce the error?

**Comment by Pomevak** [comment]
> @Pomevak I haven't heard from @thiraphong-c. Can you please open an issue on the NextJs repository with steps to reproduce the error?

OK, I will try and see if I can make a minimal reproduction.

**Comment by Pomevak** [comment]
In `next.config.js`, I wrote

```javascript
{
    target: "serverless"
}
```

commenting this line out have solved the issue for me .

So next-i18next does not support severless mode?

**Comment by isaachinman** [comment]
@Pomevak The `next-i18next` package _definitely_ supports serverless deployments, and the example itself is hosted on Vercel.

You can see an explanation about the `target: "serverless"` config option [here](https://github.com/vercel/next.js/issues/20790#issuecomment-755178273). Basically – don't use it.
