### ISSUE TITLE
next-i18next version update - Cannot find module 'next-i18next/middleware'

### ISSUE THREAD

**Issue by nataliaroque77** [isaachinman/next-i18next#841]
## Describe the bug
importing "next-i18next/middleware" in custom server  works fine in  "next-i18next ^4.2.1", but fails in latest version

server/index.ts:3:35 - error TS2307: Cannot find module 'next-i18next/middleware' or its corresponding type declarations.

import nextI18NextMiddleware from 'next-i18next/middleware';

## Occurs in next-i18next version
"next-i18next": "^6.0.3"

**Comment by rafael-sa** [comment]
Why was it closed? What is the instruction? 
The same has happened in a project I started to touch. 

But curiously, if I simply disable the call to this middleware, the project works with the translations applied in the server (which is custom). I wonder why is this middleware for? I can't find anything in the docs.

**Comment by nataliaroque77** [comment]
I don't know why it was closed without comment or a link to a similar issue.

middleware file doesn't exist in next-i18next latest version

**Comment by eunsukimme** [comment]
@nataliaroque77 In my opinion, similar issues were already discussed before. You can find the answer of @isaachinman 
 on https://github.com/isaachinman/next-i18next/issues/833

**Comment by nataliaroque77** [comment]
Thank @eunsukimme for let me know about #833
Great news about custom server no longer need it for next-i18next latest version.
