### ISSUE TITLE
How to setup type of an array?

### ISSUE THREAD

**Issue by ymcheung** [isaachinman/next-i18next#1199]
## Describe the bug
I was going to use an array of objects in language json file:
```
"document":
  {
    "items":
    [
      {
        "name":
          "name 0",
        "description":
          "description 0"
      },
      {
        "name":
          "name 1",
        "description":
          "description 1"
      }
    ]
  }
```
and display them with:
```
type itemProps = {
  name: string;
  description: string;
  index: number;
};

{t<itemProps[]>('document.items', {returnObjects: true}).map(({ name, description, index }: itemProps) => (
  <li key={index}>
     <strong dangerouslySetInnerHTML={{__html: name}} />
     <Paragraph dangerouslySetInnerHTML={{__html: description}} />
   </li>
   )
)}
```
Tags and contents are loaded correctly, but with type errors:
```
Type 'itemProps[]' does not satisfy the constraint 'string | TemplateStringsArray'.
  Property 'raw' is missing in type 'itemProps[]' but required in type 'TemplateStringsArray'.
```
and for `.map`
```
Property 'map' does not exist on type 'TFunctionResult'.
  Property 'map' does not exist on type 'string'.ts(2339)
```
`{t<itemProps[]>(...).map ...` worked in previous version `(6.0.2)`

How to define the types in 8.2.0? Thank you!

## Occurs in next-i18next version
`next-i18next 8.2.0`
 with `Next.js 10.2` & `TypeScript 4.2.4`

## Steps to reproduce
Copy and paste the `{t<itemProps[]>(...).map ...` above in a `.tsx` file

## Expected behaviour
No TypeScript errors

## OS (please complete the following information)
 - Device: Macbook Pro Late 2013, macOS 10.15.7
 - Browser: Brave Browser (Chrome DevTools 90)

**Comment by isaachinman** [comment]
Hi there, this question would be better suited for the [i18next repo](https://github.com/i18next/i18next). Thanks!

**Comment by danitrod** [comment]
same here, any luck with that @ymcheung ?

**Comment by ymcheung** [comment]
I use the following for now:
```
type itemProps = {
  [x: string]: any;
};
```
Still looking for a better way.

**Comment by ymcheung** [comment]
@danitrod not sure if you have resolved this but I found this working:

```
{t<string, itemProps[]>('document.items', {returnObjects: true}).map(({ name, description, index }) => (
  <li key={index}>
     <strong dangerouslySetInnerHTML={{__html: name}} />
     <Paragraph dangerouslySetInnerHTML={{__html: description}} />
   </li>
   )
)}
```
then there's no need for
```
type itemProps = {
  [x: string]: any;
};
```

From:
https://stackoverflow.com/questions/69225989/typescript-i18next-does-not-satisfy-the-constraint-string-templatestringsarra
